config/routes.rb
KnowledgeBase::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :admins
  devise_for :users

  
  
  namespace :admin do
    resources :users 
    resources :admins
  end
  
  resources :posts
  resources :pages
  
  root to: "pages#index"
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable,
         :rememberable, :trackable, :validatable
         
  attr_accessible :email, :password, :password_confirmation
         
end

app/models/attachment.rb
class Attachment < ActiveRecord::Base

  attr_accessible :attachable_id, :attachable_type, :image
  belongs_to :attachable, :polymorphic => true
  mount_uploader :file, FileUploader

end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, :to => :data

  validates_presence_of :data
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, :mount_on => :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, :mount_on => :data_file_name

  def url_content
    url(:content)
  end
end

app/models/post.rb
class Post < ActiveRecord::Base

  attr_accessible :title, :description, :steps_attributes
  has_many :steps 
  accepts_nested_attributes_for :steps, :allow_destroy => true, :reject_if => :all_blank 

end

app/models/step.rb
class Step < ActiveRecord::Base

  attr_accessible :title, :description
  belongs_to :post

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  attr_accessible  :email, :password, :password_confirmation, :remember_me
end

app/controllers/admin/admins_controller.rb
class Admin::AdminsController < ApplicationController
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_filter :authenticate_user!, expect: :index
  before_filter :load_post, :only => %w(edit update show destroy)
  
  def index
    @posts = Post.all
  end
  
  def create
    @post = Post.new(params[:post])
    if @post.save
      redirect_to new_post_path, notice: "Post creation successfull"
    else
      render :new, notice: "Something went wrong, please try again"
    end
  end
  
  def new
    @post = Post.new
    @attachable = find_attachable
  end

  def update
    if @post.update_attributes(params[:post])
      redirect_to posts_path, notice: "Post updated successfully"
    else
      render :edit, notice: "Something went wrong, please try again"
    end
  end
  
  def destroy
    @post.destroy
    redirect_to posts_path, notice: 'Record was deleted successfully'
  end

  def find_attachable
    params.each do |name, value|
      if name =~ /(.+)_id$/
        return $1.classify.constantize.find(value)
      end
    end
    nil
  end
  
  private
  
    def load_post
      @post = Post.find(params[:id]) 
    end
  
end

app/helpers/admin/admins_helper.rb
module Admin::AdminsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admin/admins/_form.html.haml
= form_for [:admin, @admin], :html => { :class => 'form-horizontal' } do |f|
  = render "shared/error_messages", :object => @admin
  .control-group
    = f.label :email, :class => 'control-label'
    .controls
      = f.text_field :email, :class => 'text_field'
  .control-group
    = f.label :password, :class => 'control-label'
    .controls
      = f.text_field :password, :class => 'text_field'
  .control-group
    = f.label :password_confirmation, :class => 'control-label'
    .controls
      = f.text_field :password_confirmation, :class => 'text_field'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), admin_admins_path, :class => 'btn'                           |

app/views/admin/admins/edit.html.haml
- model_class = Admin
.page-header
  %h1= t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
.custom_note_alert.alert-info.alert
  Leave the Password fields blank if you don't want to update the password
= render :partial => 'form'

app/views/admin/admins/index.html.haml
- model_class = Admin
.page-header
  %h1= t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:email)
      %th= model_class.human_attribute_name(:current_sign_in_at)
      %th= model_class.human_attribute_name(:last_sign_in_at)
      %th= model_class.human_attribute_name(:created_at)
      %th= t '.actions', :default => t("helpers.actions")
  %tbody
    - @admins.each do |admin|
      %tr
        %td= link_to admin.email, admin_admin_path(admin)
        %td= admin.current_sign_in_at.strftime("%A, %d %B %Y") unless admin.current_sign_in_at.blank?
        %td= admin.last_sign_in_at.strftime("%A, %d %B %Y") unless admin.last_sign_in_at.blank?
        %td= admin.created_at.strftime("%A, %d %B %Y")
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_admin_admin_path(admin), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), admin_admin_path(admin), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'                                                                         |
= will_paginate @admins
= link_to t('.new', :default => t("helpers.links.new")), |
  new_admin_admin_path,                                  |
  :class => 'btn btn-primary'                            |

app/views/admin/admins/new.html.haml
- model_class = Admin
.page-header
  %h1= t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => 'form'

app/views/admin/admins/show.html.haml
- model_class = Admin
.page-header
  %h1= t '.title', :default => model_class.model_name.human.titleize
%dl.dl-horizontal
  %dt
    %strong
      = model_class.human_attribute_name(:email)
      \:
  %dd= @admin.email
  %dt
    %strong
      = model_class.human_attribute_name(:encrypted_password)
      \:
  %dd= @admin.encrypted_password
  %dt
    %strong
      = model_class.human_attribute_name(:current_sign_in_at)
      \:
  %dd= @admin.current_sign_in_at.strftime("%A, %d %B %Y")
  %dt
    %strong
      = model_class.human_attribute_name(:last_sign_in_at)
      \:
  %dd= @admin.last_sign_in_at.strftime("%A, %d %B %Y")
  %dt
    %strong
      = model_class.human_attribute_name(:current_sign_in_ip)
      \:
  %dd= @admin.current_sign_in_ip
  %dt
    %strong
      = model_class.human_attribute_name(:last_sign_in_ip)
      \:
  %dd= @admin.last_sign_in_ip
  %dt
    %strong
      = model_class.human_attribute_name(:created_at)
      \:
  %dd= @admin.created_at.strftime("%A, %d %B %Y")
.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), admin_admins_path, :class => 'btn'                       |
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_admin_admin_path(@admin), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), admin_admin_path(@admin), :method => 'delete', :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },:class => 'btn btn-danger'

app/views/admin/users/_form.html.haml
= form_for [:admin, @user], :html => { :class => 'form-horizontal' } do |f|
  = render "shared/error_messages", :object => @user

  .control-group
    = f.label :email, :class => 'control-label'
    .controls
      = f.text_field :email, :class => 'text_field'
  
  .control-group
    = f.label :password, :class => 'control-label'
    .controls
      = f.password_field :password
  .control-group
    = f.label :password_confirmation, :class => 'control-label'
    .controls
      = f.password_field :password_confirmation
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), |
      admin_users_path, :class => 'btn'

app/views/admin/users/edit.html.haml
- model_class = User
.page-header
  %h1= t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
.custom_note_alert.alert-info.alert
  Leave the Password fields blank if you don't want to update the password  
= render :partial => 'form'

app/views/admin/users/new.html.haml
- model_class = User
.page-header
  %h1= t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => 'form'

app/views/admin/users/show.html.haml
- model_class = User
.page-header
  %h1= t '.title', :default => model_class.model_name.human.titleize
%h3 Basic Information
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:email)
      %th= model_class.human_attribute_name(:provider)
      %th= model_class.human_attribute_name(:last_sign_in_at)
      %th= model_class.human_attribute_name(:last_sign_ip)
      %th= model_class.human_attribute_name(:created_at)
      %th= t '.actions', :default => t("helpers.actions")
  %tbody
    %tr
      %td= @user.email
      %td= (@user.provider.blank?) ? 'General Registration' : @user.provider
      %td= @user.last_sign_in_at.strftime("%Y-%m-%d") unless @user.last_sign_in_at.blank?
      %td= @user.last_sign_in_ip  
      %td= @user.created_at
      %td
        = link_to t('.edit', :default => t("helpers.links.edit")), edit_admin_user_path(@user), :class => 'btn'
        = link_to t('.destroy', :default => t("helpers.links.destroy")), admin_user_path(@user), :method => 'delete', :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'
%dl.dl-horizontal
  - unless @user.profile.blank?
    %h3 Profile Information
    %table.table.table-striped
      %thead
        %tr
          %th= model_class.human_attribute_name(:first_name)
          %th= model_class.human_attribute_name(:last_name)
          %th= model_class.human_attribute_name(:dob)
          %th= model_class.human_attribute_name(:gender)
          %th= model_class.human_attribute_name(:city)
          %th= model_class.human_attribute_name(:state)
          %th= model_class.human_attribute_name(:country)
          %th= model_class.human_attribute_name(:zip)
      %tbody
        %tr
          %td= @user.profile.first_name.blank? ? "-" : "#{@user.profile.first_name}"
          %td= @user.profile.last_name.blank? ? "-" : "#{@user.profile.last_name}"
          %td= @user.profile.dob.blank? ? "-" : "#{@user.profile.dob.strftime("%Y-%m-%d")}"
          %td= @user.profile.gender.blank? ? "-" : "#{@user.profile.gender}"
          %td= @user.profile.city.blank? ? "-" : "#{@user.profile.city}"
          %td= @user.profile.state.blank? ? "-" : "#{@user.profile.state}"
          %td= @user.profile.country.blank? ? "-" : "#{@user.profile.country}"
          %td= @user.profile.zip.blank? ? "-" : "#{@user.profile.zip}"
            
  - unless @user.resumes.blank?
    %h3
      Resumes Attached
    %table.table.table-striped
      - @user.resumes.each do |r|
        %tr
          %td
            %i.icon-file
            = r.resume_file_name
          %td
          %td  
            = link_to "Tracking Details", admin_trackers_path(:rid => r), :class => 'btn btn-primary' 
            
  -unless @user.subject_lines.blank?
    %h3 
      Subject Lines
    %table.table.table-striped
      %tr
      - @user.subject_lines.each do |email_attribute|          
        %tr
          %td
            = email_attribute.description 
  -unless @user.cover_letters.blank?
    %h3 Cover Letters
    %table.table.table-striped
      %tr
      - @user.cover_letters.each do |email_attribute|          
        %tr
          %td
            = email_attribute.description  
  -unless @user.email_accounts.blank?
    %h3 Email Accounts
    %table.table.table-striped
      - @user.email_accounts.each do |email_account|          
        %tr
          %td
            = image_tag("#{email_account.service}-logo.png")
.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), admin_users_path, :class => 'btn'

app/views/admins/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/layouts/admin.html.haml
!!!
%html
  %head
    %title KnowledgeBase
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    = link_to "Sign Out",destroy_admin_session_path, method: :delete unless current_admin.blank?
    = yield

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>KnowledgeBase</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title KnowledgeBase
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    = link_to "Sign Out",destroy_user_session_path, method: :delete unless current_user.blank?
    = link_to "Sign Out",destroy_admin_session_path, method: :delete unless current_admin.blank?
    = yield

app/views/pages/index.html.haml
%h1 Welcome

app/views/posts/_form.html.haml
= nested_form_for @post do |f|
  %p
    = f.label :title
    %br/
    = f.text_field :title
  %p
    = f.label :description
    %br/
    = f.cktext_area :description, id: 'sometext', ckeditor: {uiColor: '#040605', toolbar: 'mini'}
  = f.fields_for :steps do |step_form|
    %p
      = step_form.label :title
      %br/
      = step_form.text_field :title
    %p 
      = step_form.label :description
      %br/
      = step_form.cktext_area :description, id: 'step_description', ckeditor: {uiColor: '#040605', toolbar: 'mini'}
    %p
      = step_form.link_to_remove "Remove this step"
  %p
    = f.link_to_add "Add a step", :steps
  %p
    = f.submit  

app/views/posts/edit.html.haml
%h1
  Edit post
  
= render "form"

app/views/posts/index.html.haml
%h1
  Welcome to Knowledge base
  
- @posts.each do |post|
  %b Title
  = post.title
  %b Description
  = post.description
  %br

app/views/posts/new.html.haml
%h1
  Create a new post
= render "form"

app/views/posts/show.html.haml
%b
  Title:
= @post.title
%br
%b
  Description:
= @post.description

app/views/shared/_error_messages.html.haml
.error_messages
  - if object.errors.any?
    .alert.alert-danger
      - object.errors.full_messages.each do |msg|
        = msg
        %br/

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>